---
# tasks file for install_vsftpd/
- name: Install "{{ service }}"
  yum:
    name: "{{ service }}"
    state: latest

- name: Start and enable service
  service:
    name: "{{ service }}"
    state: started
    enabled: true
  

- name: open port
  firewalld:
    service: ftp
    immediate: yes
    permanent: yes
    state: enabled

- name: Install configuration file
  template:
    src: vsftpd.j2    
    dest: /etc/vsftpd/vsftpd.conf
    mode: '0600'
  notify:
    - restart_vsftpd 

- name: Creating directory /var/ftp/pub
  file: 
    path: /var/ftp/pub
    state: directory
    mode: '0777'
    owner: ftp

- name: Creating directory /var/ftp/pub/upload
  file:    
    setype: "public_content_rw_t"
    seuser: "system_u"
    path: /var/ftp/pub/upload
    recurse: yes
    owner: ftp
 


- name: Install libselinux
  yum:
    name: python3-libselinux
    state: present

- name: Install libmanage  
  yum: 
    name: python3-libsemanage 
    state: present



- name: set selinux boolean
  seboolean:
    name: ftpd_anon_write
    state: yes
    persistent: yes
  tags: vsftp
  notify:
    - restorecon
  
